


# Permalinks
permalink:        pretty

# Setup
title:            XML utilities
tagline:          'Serialize valid XML from parsed Scala objects'
description:      ''


baseurl: '/xmlutils/'


author:
  name:           'Neel Smith'


links:
  - title:  Github repository for xmlutils
    url:  https://github.com/neelsmith/xmlutils
    external: true
